// Generated by scripts/generate-sections.mjs from
// integrations/wordpress/nexuscontent/sections.json. Do not edit by hand.
// Run `npm run generate:sections` after changing the JSON; CI enforces
// freshness with `npm run check:sections`.

type GeneratedJson = null | boolean | number | string | GeneratedJson[] | { [key: string]: GeneratedJson };

export interface GeneratedSectionFieldDefinition {
  readonly name: string;
  readonly type: "string" | "number" | "boolean" | "json" | "media";
  readonly required?: boolean;
  readonly default?: GeneratedJson;
}

export type GeneratedSectionType = "hero" | "intro" | "rich_text" | "image_text" | "features" | "statistics" | "testimonials" | "gallery" | "cta" | "faq" | "logo_grid" | "form_embed";

export const WORDPRESS_SECTION_NAMES: Readonly<Record<GeneratedSectionType, string>> = {
  "hero": "hero",
  "intro": "intro",
  "rich_text": "rich-text",
  "image_text": "image-text",
  "features": "features",
  "statistics": "statistics",
  "testimonials": "testimonials",
  "gallery": "gallery",
  "cta": "cta",
  "faq": "faq",
  "logo_grid": "logo-grid",
  "form_embed": "form-embed",
};

export const BUILTIN_SECTION_FIELDS: Readonly<
  Record<GeneratedSectionType, readonly GeneratedSectionFieldDefinition[]>
> = {
  "hero": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "body", type: "string" },
    { name: "image", type: "media" },
    { name: "buttons", type: "json" }
  ],
  "intro": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "body", type: "string" },
    { name: "image", type: "media" },
    { name: "image_position", type: "string" }
  ],
  "rich_text": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "heading", type: "string" },
    { name: "body", type: "string" }
  ],
  "image_text": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "body", type: "string" },
    { name: "image", type: "media" },
    { name: "image_position", type: "string" },
    { name: "buttons", type: "json" }
  ],
  "features": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "body", type: "string" },
    { name: "items", type: "json" }
  ],
  "statistics": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "items", type: "json" }
  ],
  "testimonials": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "items", type: "json" }
  ],
  "gallery": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "images", type: "json" }
  ],
  "cta": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "heading", type: "string" },
    { name: "body", type: "string" },
    { name: "buttons", type: "json" },
    { name: "background_image", type: "media" }
  ],
  "faq": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "items", type: "json" }
  ],
  "logo_grid": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "eyebrow", type: "string" },
    { name: "heading", type: "string" },
    { name: "items", type: "json" }
  ],
  "form_embed": [
    { name: "section_id", type: "string" },
    { name: "variant", type: "string" },
    { name: "heading", type: "string" },
    { name: "provider", type: "string" },
    { name: "form_id", type: "string" },
    { name: "embed_code", type: "string" }
  ],
};

export const FIXED_SECTION_TYPES = ["hero", "intro", "cta"] as const;
